GET http://localhost:3001/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2F0eWEiLCJpYXQiOjE2NzYzMDcxNjF9.TTodpOQpfb-R3OdMHhpk8qui4Wzu4uMDTPH_GwiSmlo

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "user":{
        "name":"Katya",
        "email":"123",
    }
}
